# Generated by Django 5.2.7 on 2025-10-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium')], default='pending', max_length=20),
        ),
    ]
